# Generated by Django 5.2.4 on 2025-07-21 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Komponen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matgroup_id', models.IntegerField()),
                ('material_id', models.CharField(max_length=100, unique=True)),
                ('material_name', models.CharField(max_length=255)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('safety_stock', models.IntegerField(default=0)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('type_id', models.IntegerField(blank=True, null=True)),
                ('is_disposable', models.BooleanField(default=False)),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('cat_id', models.IntegerField(blank=True, null=True)),
                ('group_id', models.IntegerField(blank=True, null=True)),
                ('stock', models.IntegerField(default=0)),
                ('broken_stock', models.IntegerField(default=0)),
                ('types', models.CharField(blank=True, max_length=100, null=True)),
                ('cat_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Komponen',
                'verbose_name_plural': 'Komponen',
            },
        ),
        migrations.CreateModel(
            name='Komputer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sap_code', models.CharField(blank=True, max_length=100, null=True)),
                ('dal_code', models.CharField(max_length=100, unique=True)),
                ('inventory_code', models.CharField(blank=True, max_length=100, null=True)),
                ('machine_name', models.CharField(max_length=255)),
                ('acquisition_year', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('cost_center', models.CharField(blank=True, max_length=100, null=True)),
                ('operator_name', models.CharField(max_length=100)),
                ('machine_condition', models.CharField(choices=[('A', 'Baik Sekali'), ('B', 'Baik'), ('C', 'Kurang Baik'), ('D', 'Rusak')], default='B', max_length=50)),
                ('group_id', models.IntegerField()),
                ('group_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Komputer',
                'verbose_name_plural': 'Komputer',
            },
        ),
        migrations.CreateModel(
            name='RiwayatKerusakan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('deskripsi', models.TextField()),
                ('komputer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_kerusakan', to='inventory.komputer')),
            ],
            options={
                'verbose_name': 'Riwayat Kerusakan',
                'verbose_name_plural': 'Riwayat Kerusakan',
            },
        ),
        migrations.CreateModel(
            name='RiwayatPerawatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('deskripsi', models.TextField()),
                ('komputer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_perawatan', to='inventory.komputer')),
            ],
            options={
                'verbose_name': 'Riwayat Perawatan',
                'verbose_name_plural': 'Riwayat Perawatan',
            },
        ),
        migrations.CreateModel(
            name='PerawatanKomponen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_digunakan', models.IntegerField(default=1)),
                ('komponen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.komponen')),
                ('riwayat_perawatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.riwayatperawatan')),
            ],
            options={
                'verbose_name': 'Komponen Digunakan',
                'verbose_name_plural': 'Komponen Digunakan',
                'unique_together': {('riwayat_perawatan', 'komponen')},
            },
        ),
    ]
